title: Networks Reading Group 2021
url: "https://ankitsultana.com"
baseurl: "/Networks"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

# footer: yes
# footer_url: "https://github.com/ankitsultana"
# footer_text: "Page design by Ankit Sultana"


sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/Networks/"
 - name: "Reading List"
   link: "Networks RG_Winter 2021.pdf"
 - name: "Contact"
   link: "contact"
